import { Request, Response } from 'express'
import { Challenge } from '../models/Challenge'

// POST /api/challenges — creates a new challenge, returns its shareable ID
export async function createChallenge(req: Request, res: Response) {
  const { title, description, language, starterCode, testCases } = req.body

  if (!title || !description || !starterCode || !testCases) {
    return res.status(400).json({ error: 'Missing required challenge fields' })
  }

  try {
    const challenge = await Challenge.create({
      title,
      description,
      language: language || 'javascript',
      starterCode,
      testCases,
    })

    // challenge._id is auto-generated by MongoDB — this becomes the shareable link
    res.status(201).json({
      id: challenge._id,
      shareableLink: `/solve/${challenge._id}`,
    })
  } catch (error: any) {
    console.error('Error creating challenge:', error.message)
    res.status(500).json({ error: 'Failed to create challenge' })
  }
}

// GET /api/challenges/:id — fetch one challenge by its ID (for the solver's view)
export async function getChallenge(req: Request, res: Response) {
  const { id } = req.params

  try {
    const challenge = await Challenge.findById(id)

    if (!challenge) {
      return res.status(404).json({ error: 'Challenge not found' })
    }

    // Only send what the solver needs — never send hidden test case data
    res.json({
      id: challenge._id,
      title: challenge.title,
      description: challenge.description,
      language: challenge.language,
      starterCode: challenge.starterCode,
      visibleTestCases: challenge.testCases
        .filter((tc) => !tc.hidden)
        .map((tc) => ({ input: tc.input, expectedOutput: tc.expectedOutput })),
    })
  } catch (error: any) {
    // A malformed id (not a valid MongoDB ObjectId) throws here — treat it as "not found"
    console.error('Error fetching challenge:', error.message)
    res.status(404).json({ error: 'Challenge not found' })
  }
}
